export const icons = {
  documents: 'far fa-file',
  signed: 'fas fa-file-signature',
  send: 'far fa-paper-plane',
  draft: 'fa-light fa-file',
  received: 'fas fa-envelope-open-text',
  contacts: 'far fa-id-badge',
  closeIcon: 'fas fa-times',
  logout: 'fas fa-sign-out-alt',
  tools: 'fas fa-tools',
  pen: 'fas fa-pen',
  trashcan: 'fas fa-trash-alt',
  camera: 'fas fa-camera',
  user: 'fas fa-user',
  spreadsheet: 'fas fa-file-excel',
  fileUpload: 'fas fa-file-upload',
  name: 'fas fa user',
  calendar: 'far fa-calendar',
  text: 'fas fa-text',
  download: 'fas fa-download',
  eye: 'fas fa-eye',
  pendingCircle: 'fas fa-exclamation-circle',
  completedCircle: 'fas fa-check-circle',
  waitingCircle: 'fa fa-exclamation-triangle',
  previous: 'fas fa-angle-double-left',
  next: 'fas fa-angle-double-right',
  menu: 'fas fa-ellipsis-v',
  plus: 'fas fa-plus',
  minus: 'fas fa-minus',
  linkedin: 'fab fa-linkedin',
  github: 'fab fa-github'
}
