export const icons = {
  documents: "far fa-file",
  signed: "fas fa-file-signature",
  send: "far fa-paper-plane",
  draft: "fa-light fa-file",
  received: "fas fa-envelope-open-text",
  contacts: "far fa-id-badge",
  plus: "fas fa-file-upload",
  closeIcon: "fas fa-times",
  logout: "fas fa-sign-out-alt",
  tools: "fas fa-tools",
  pen: "fas fa-pen",
  trashcan: "fas fa-trash-alt",
  camera: "fas fa-camera",
  user: "fas fa-user-plus",
  spreadsheet: "fas fa-file-excel",
  fileUpload: "fas fa-file-upload",
  name: "fas fa user",
  calendar: "far fa-calendar",
  text: "fas fa-text",
  download: "fas fa-download",
  eye: "fas fa-eye",
  exclamationCircle: "fas fa-exclamation-circle",
  checkCircle: "fas fa-check-circle",
  previous: "fas fa-angle-double-left",
  next: "fas fa-angle-double-right",
  menu: "fas fa-ellipsis-v",
};
